version: '3.9'

volumes:
  todo_data:
    name: ${DB_VOLUME_NAME} # collected from .env file

services:

  todo-app-db:
    container_name: todo-app-db
    hostname: todo-app-db
    image: mongo:4.2.6
    env_file: './db-container-dev.env'
    volumes:
      - ./app/db/local.mongod.conf:/etc/mongod.conf
      - ./app/db/log:/var/log/mongodb/
      - todo_data:/data/db
    ports:
      - ${DB_PORT}:${DB_PORT} # collected from .env file
    networks:
      - todo-app-dev
    command: ["-f", "/etc/mongod.conf"]

  todo-app-server:
    container_name: todo-app-server
    env_file: './app-container-dev.env'
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - ${PORT}:${PORT} # collected from .env file
    networks:
      - todo-app-dev
    command: "npm run start:container-dev"



networks:
  todo-app-dev:
