version: '3.9'

services:

  todo-app-db:
    container_name: todo-app-db
    hostname: todo-app-db
    image: mongo:4.2.6
    env_file: './app/db/dev.env'
    volumes:
      - ./app/db/local.mongod.conf:/etc/mongod.conf
      - ./app/db/log:/var/log/mongodb/
    ports:
      - '27017:27017'
    networks:
      - todo-app-dev
    command: ["-f", "/etc/mongod.conf"]  

  todo-app-server:
    container_name: todo-app-server
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - '3000:3000'
    networks:
      - todo-app-dev      

  

networks:
  todo-app-dev:  