FROM node:lts-alpine3.9
LABEL MAINTAINER="Jannes Brunner"

# copy both 'package.json' and 'package-lock.json' (if available)
COPY package*.json ./

# install project dependencies
RUN npm install

# copy project files and folders to the current working directory (i.e. 'app' folder)
COPY . .

EXPOSE 3000

CMD [ "npm", "run", "start:container-dev" ]
