FROM node:lts-alpine3.9
LABEL MAINTAINER="Jannes Brunner"

WORKDIR /client

# copy both 'package.json' and 'package-lock.json' (if available)
COPY ./package*.json ./

# install project dependencies
RUN npm install

COPY . .
