FROM node:lts-alpine3.9

# install simple http server for serving build content
RUN npm install -g http-server

# copy both 'package.json' and 'package-lock.json' (if available)
COPY package*.json ./

# install project dependencies
RUN npm install

# copy project files and folders to the current working directory (i.e. 'app' folder)
COPY . .

# build app for production
RUN npm run build

# test app for production
# RUN npm run test

EXPOSE 8080

CMD [ "http-server", "build" ]
