FROM node:lts-alpine3.9 as todo-app-client-build
LABEL MAINTAINER="Jannes Brunner"

WORKDIR /client

# copy both 'package.json' and 'package-lock.json' (if available)
COPY package*.json ./

# install project dependencies
RUN npm install

COPY ./public ./public

COPY ./src ./src

COPY ./scripts ./scripts

COPY ./config ./config

# build app for production
RUN npm run build

FROM nginx:latest

COPY --from=todo-app-client-build /client/build/ /usr/share/nginx/html

EXPOSE 80
