set -e

echo AWS_ACCESS_KEY_ID
read INPUT_AAKI

echo AWS_SECRET_ACCESS_KEY
read INPUT_ASAK

echo AWS_SESSION_TOKEN
read INPUT_AST

export AWS_ACCESS_KEY_ID=$INPUT_AAKI
export AWS_SECRET_ACCESS_KEY=$INPUT_ASAK
export AWS_SESSION_TOKEN=$INPUT_AST